### ISSUE TITLE
Palette-Addresses.xdata missing

### ISSUE THREAD

**Issue by SmiteIsTrashBro** [huguesjohnson/eisfrei#2]
Hi, you forgot to provide the file "Eisfrei-v11\data\Palette-Addresses.xdata".
![image](https://user-images.githubusercontent.com/28743155/59456754-6bfcb580-8ded-11e9-9975-67f2446c5c08.png)

**Comment by huguesjohnson** [comment]
Sorry about that, I just re-uploaded the .zip on the project page.
